apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: beacon-port
  selector:
    app: {{ .Values.appName }}


